config/routes.rb
Agitosemana::Application.routes.draw do
  match "garota" => 'garota#index'

  get "busca/resultados"

  get "login/index"
  
  match "principal" => 'home#principal', :as => :principal

  match "albuns-de/:user_id" => 'albuns#index', :as => :albuns
  match "albuns/detalhes/:id" => 'albuns#detalhes', :as => :detalhes_album
  match "albuns/criar" => 'albuns#criar', :as => :criar_album, :via => :post
  match "albuns/:album_id/adicionar-fotos" => 'albuns#adicionar_fotos', :as => :adicionar_fotos
  match "albuns/:album_id/salvar-foto" => 'albuns#salvar_foto', :as => :salvar_foto, :via => :post
  
  match "albuns/:album_id/:id/remover-foto" => 'albuns#remover_foto', :as => :remover_foto
  

  match "albuns/:album_id/ver-foto/:id" => 'albuns_fotos#ver', :as => :album_ver_foto
  match 'albuns/salvar-marcacao' => 'albuns_fotos#salvar_marcacao', :as => :album_salvar_marcacao, :via => :get
  match 'albuns/remover-marcacao' => 'albuns_fotos#remover_marcacao', :as => :album_remover_marcacao, :via => :get
  match 'albuns/fotos/marcacoes' => 'albuns_fotos#marcacoes', :as => :album_marcacoes, :via => :get

  match "entrar" => 'usuarios#index', :as => :entrar
  
  match "registrar" => "usuarios#registrar", :as => :usuarios_registrar

  post "usuarios/entrar"
  
  post "usuarios/criar"
  
  get "usuarios/autocomplete"
  
  match "sair" => "usuarios#sair", :as => :usuarios_sair

  match "chame-agito" => "agito#chame_agito", :as => 'chame_agito'
  match "chame-agito/enviar" => "agito#enviar_chame_agito", :as => 'enviar_chame_agito'
  

  match "fale-conosco" => "agito#fale_conosco", :as => 'fale_conosco'
  match "fale-conosco/enviar" => "agito#enviar_fale_conosco", :as => 'enviar_fale_conosco', :via => :post

  match "15-anos" => "agito#index_15_anos", :as => 'index_15_anos'
  match "15-anos/enviar" => "agito#enviar_15_anos", :as => 'enviar_15_anos'

  match "noticias" => "noticias#index", :as => 'noticias'
  match "noticias/detalhes/:id" => "noticias#detalhes", :as => 'detalhes_noticia'

  match "videos" => "videos#index", :as => 'videos'
  get "videos/detalhes"

  match "agendas" => "agendas#index", :as => 'agendas'
  match "agendas/detalhes/:id" => "agendas#detalhes", :as => 'detalhes_agenda'

  match "galerias" => "galerias#index", :as => :galerias
  match "galerias/detalhes/:id" => 'galerias#detalhes', :as => :detalhes_galeria
  match "galerias/:gallery_id/ver-foto/:id" => 'galerias_fotos#ver', :as => :galeria_ver_foto
  match "galerias/:gallery_id/comentar-foto/:id" => 'galerias_fotos#comentar', :as => :galeria_comentar_foto

  match "colirios" => "colirios#index", :as => :colirios
  match "colirios/detalhes/:id" => 'colirios#detalhes', :as => :detalhes_colirio
  
  
  match "revistas" => "revistas#index", :as => 'revistas'
  match "revistas/detalhes/:id" => "revistas#detalhes", :as => 'detalhes_revista'

  namespace :admin do
    root :to => "events#index"
    
    match 'login/index'               => 'login#index',   :as => :login
    match 'login/logout'              => 'login#logout',  :as => :logout
    match 'login/enter'               => 'login#enter',   :as => :login_enter, :via => :post
    
    
    resources :events
    resources :event_categories
    
    resources :user_albuns
    resources :galleries do
      resources :gallery_images do
        member do
          get :make_special
        end
      end
    end
    resources :gallery_categories
    
    resources :videos
    resources :video_categories
    
    resources :places
    
    resources :polls
    
    resources :news
    resources :news_categories
    resources :column_text_news
    resources :columnists
    
    resources :banners
    resources :magazines
    
    resources :users
    
    
  end
  

  root :to => 'home#index'
end

app/models/gallery.rb
# -*- encoding : utf-8 -*-
require 'rubygems'
require 'zip/zip'
require 'fileutils'

class Gallery < ActiveRecord::Base
  module Types
    COMMON, COLLYRIUM = 0, 1
  end
  default_scope order('realized_at DESC')
  scope :collyrium, where(:type_gallery => Gallery::Types::COLLYRIUM).where("image_front_file_name IS NOT NULL")
  scope :common, where(:type_gallery => Gallery::Types::COMMON).where("image_front_file_name IS NOT NULL")
  belongs_to :event
  belongs_to :place
  belongs_to :gallery_category
  belongs_to :gallery_image
  has_many :gallery_images, :dependent => :destroy
  has_many :gallery_comments, :through => :gallery_images, :source => :gallery_image_comments
  attr_accessor :folder_with_images
  attr_accessible :description, :photographers, :realized_at, :title, :type_gallery, :event_id, :place_id, :gallery_category_id, :compacted, :image_front, :folder_with_images
  has_attached_file :compacted
  
  # home: utilizada para imagem pequena na home
  # home_big: colirio na home
  # big: destaque na pagina da galeria
  has_attached_file :image_front, :styles => {:home => '238x92#', :home_big => '750x300', :big => "400x400>"}
  # 
  # validates_attachment_presence :image_front
  
  validates_presence_of :title, :realized_at, :description, :gallery_category, :type_gallery
  # after_save :save_images_in_folder
  
  def to_param
    [self.id,self.title.parameterize].join('-')
  end
  
  def save_images_in_folder
    unless self.folder_with_images.blank?
      directory_with_images = File.join(Rails.root,'fotos',self.folder_with_images,"*.jpg")
      files = Dir.glob(directory_with_images)
      files.each do |f_path|
        new_file_name = File.join(Rails.root,'fotos',self.folder_with_images,"#{self.to_param[0,10]}-#{Time.now.to_i}-#{File.basename(f_path)}")
        FileUtils.mv(f_path,new_file_name)
        GalleryImage.transaction do
          begin
            gallery_image = self.gallery_images.build(:image => File.open(new_file_name))
            gallery_image.save!
            File.unlink(new_file_name)
          rescue
            FileUtils.mv(new_file_name,f_path)
          end
        end
      end

      # tmp_gallery_path = "#{Rails.root}/tmp/gallery_#{self.id}/"
      # FileUtils.mkdir_p(tmp_gallery_path) unless File.directory?(tmp_gallery_path)
      # files = []
      # Zip::ZipFile.open(self.compacted.path) do |zip_file|
      #   zip_file.each do |f|
      #     f_path=File.join(tmp_gallery_path, f.name)
      #     FileUtils.mkdir_p(File.dirname(f_path))
      #     zip_file.extract(f, f_path) unless File.exist?(f_path)
      #     # File.unlink(File.join(tmp_gallery_path,f.name)) if File.exist?(File.join(tmp_gallery_path,f.name))
      #     # zip_file.extract(f.name,File.join(tmp_gallery_path,f.name)) 
      #     if File.file?(f_path)
      #       files << f_path
      #     end
      #   end
      # end
      # files.each do |f_path|
      #   gallery_image = self.gallery_images.build(:image => File.open(f_path))
      #   gallery_image.save
      # end
      # FileUtils.rm_rf(tmp_gallery_path)
    end
    true
  end
end

app/controllers/admin/galleries_controller.rb
# -*- encoding : utf-8 -*-
class Admin::GalleriesController < Admin::AdminController
  # GET /admin/galleries
  # GET /admin/galleries.json
  def index
    @galleries = Gallery.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @galleries }
    end
  end

  # GET /admin/galleries/1
  # GET /admin/galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @gallery }
    end
  end

  # GET /admin/galleries/new
  # GET /admin/galleries/new.json
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @gallery }
    end
  end

  # GET /admin/galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /admin/galleries
  # POST /admin/galleries.json
  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        @gallery.save_images_in_folder
        format.html { redirect_to edit_admin_gallery_path(@gallery), :notice => 'Gallery was successfully created.' }
        format.json { render :json => @gallery, :status => :created, :location => @gallery }
      else
        format.html { render :action => "new" }
        format.json { render :json => @gallery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/galleries/1
  # PUT /admin/galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        @gallery.save_images_in_folder
        format.html { redirect_to edit_admin_gallery_path(@gallery), :notice => 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @gallery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/galleries/1
  # DELETE /admin/galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to admin_galleries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/galleries_helper.rb
# -*- encoding : utf-8 -*-
module Admin::GalleriesHelper
  def image_folders
    all_files = Dir.entries(File.join(Rails.root,'fotos'))
    folders = []
    all_files.sort!
    all_files.each do |f|
      full_path = File.join(Rails.root,'fotos',f)
      next if f == '.' || f == '..' || !File.directory?(full_path)

      directory_with_images = File.join(Rails.root,'fotos',f,"*.jpg")
      files = Dir.glob(directory_with_images)
      folders << ["#{f} - #{files.size} fotos",f]
    end
    folders
  end
end

app/views/admin/galleries/_form.html.erb
<%= simple_form_for([:admin,@gallery], :html => {:multipart => true}) do |f| %>
<div class="module_content">

  <fieldset  style="width:48%; float:left; margin-right: 31px;">
    <%= f.association :event, :collection => events_choices, :input_html => {:style => "width:92%"} %>
  </fieldset>
  <fieldset style="width:48%; float:left;">
    <%= f.association :place, :input_html => {:style => "width:92%"} %>
  </fieldset>
  
  <fieldset  style="width:48%; float:left; margin-right: 31px;">
    <%= f.association :gallery_category, :input_html => {:style => "width:92%"}  %>
  </fieldset>
  <fieldset style="width:48%; float:left;">
    <%= f.input :type_gallery, 
    :collection => [['Comum',Gallery::Types::COMMON],['Colírio',Gallery::Types::COLLYRIUM]],
    :input_html => {:style => "width:92%"}  %>
  </fieldset>
  
  <fieldset>
    <%= f.input :photographers  %>
  </fieldset>
  <fieldset>
    <%= f.input :title %>
  </fieldset>
  
  <fieldset>
    <%= f.input :image_front %>
  </fieldset>
  <% unless @gallery.image_front_file_name.blank? %>
  <center>
  <%=image_tag @gallery.image_front.url(:big)%>
  </center>
  <% end %>
  
  <fieldset>
    <%= f.input :folder_with_images,
    :collection => image_folders,
    :include_blank => true %>
  </fieldset>
  <fieldset>
    <%= f.input :description, :input_html => {:rows => 15} %>
  </fieldset>
  <fieldset>
    <%=f.input :realized_at, :input_html => {:style => 'width:auto;margin:0 2px;'} %>
  </fieldset>
</div>
<footer>
  <div class="submit_link">
    <%= f.button :submit, :value => 'Salvar', :class => 'alt_btn' %>
  </div>
</footer>
<% end %>
<% content_for :head do %>
<%= javascript_include_tiny_mce_if_used %>
<%= tiny_mce if using_tiny_mce? %>
<% end %>

app/views/admin/galleries/_form_gallery_image_comments.html.erb
<table class="tablesorter" cellspacing="0">
  <thead>
  <tr>
    <th>Autor</th>
    <th>Comentário</th>
    <th>Data</th>
    <th>Ações</th>
  </tr>
  </thead>
  <% if !@gallery.gallery_comments.blank? %>
    <% for gallery_image_comment in @gallery.gallery_comments %>
      <tr>
        <td><%=gallery_image_comment.user.name%></td>
        <td><pre><%=gallery_image_comment.comment%></pre></td>
        <td><%=l gallery_image_comment.created_at, :format => :short%></td>
      </tr>
    <% end %>
  <% else %>
    
  <% end %>
  
</table>

app/views/admin/galleries/_form_gallery_images.html.erb
<%= form_for :gallery_image, :url => admin_gallery_gallery_images_path(@gallery), :html => { :class => "upload", :multipart => true } do |f| %>
<div class="module_content">
  <fieldset>
		<%= f.file_field :image %>
  </fieldset>
</div>

<table class="tablesorter upload_files" cellspacing="0"></table>
<table class="tablesorter download_files" cellspacing="0">
  <thead>
    <tr>
      <th>Imagem da galeria</th>
      <th>Nome do arquivo</th>
      <th>Localização</th>
      <th>Ações</th>
    </tr>
  </thead>
  <% if !@gallery.gallery_images.blank? %>
    <% for gallery_image in @gallery.gallery_images %>
      <tr>
        <td><%=image_tag gallery_image.image.url(:thumb) %></td>
        <td><%=gallery_image.image_file_name%></td>
        <td><%=link_to truncate(gallery_image.image.url), gallery_image.image.url, :alt => gallery_image.image.url, :title => gallery_image.image.url %></td>
        <td>
        <%= link_to 'remover', admin_gallery_gallery_image_path(gallery_image.gallery,gallery_image), :method => :delete, :confirm => 'Tem certeza desta operação?' %>
        </td>
      </tr>
    <% end %>
  <% else %>
    
  <% end %>
  
</table>
<% end %>

<% content_for :head do %>
<%=stylesheet_link_tag 'jquery.fileupload-ui'%>
<script type="text/javascript" charset="utf-8">
$(document).ready(function(){ 
    $('.upload').fileUploadUI({
        uploadTable: $('.upload_files'),
        downloadTable: $('.download_files'),
        buildUploadRow: function (files, index) {
            var file = files[index];
            return $('<tr><td>' + file.name + '<\/td>' +
                    '<td class="file_upload_progress"><div><\/div><\/td>' +
                    '<td class="file_upload_cancel">' +
                    '<div class="ui-state-default ui-corner-all ui-state-hover" title="Cancelar">' +
                    '<span class="ui-icon ui-icon-cancel">Cancelar<\/span>' +
                    '<\/div><\/td><\/tr>');
        },
        buildDownloadRow: function (file) {
          var row = '<tr>' +
          '<td><img alt="'+file.name+'" src="'+file.thumb_path+'"></td>' + 
          '<td>'+file.name+'</td>' + 
          '<td><a href="'+file.normal_path+'" alt="'+file.normal_path+'" title="'+file.normal_path+'">'+file.normal_path.substr(0,30)+'...</a></td>' + 
          '<td></td>' + 
          '</tr>';

          return $(row);
        },
        onComplete: function(){
          // var table = $(".tablesorter");
          // table.trigger("update")
          //   // .trigger("sorton", [usersTable.get(0).config.sortList])
          //   .trigger("appendCache")
          //   .trigger("applyWidgets");
          equalHeight($('.column'));
        }
        // ,
        //        onComplete: function (event, files, index, xhr, handler) { 
        //            $.ajax({
        //              type: "GET",
        //              url: "/remote/show_pic/",
        //              success: function(data){
        //                       cropping_arrived();
        //                       }
        //              });
        //        }
    });
});
</script>
<% end %>

app/views/admin/galleries/edit.html.erb
<%
title 'Galerias - Alterando Galeria'
breadcrumbs([
  {:text => 'Galerias', :url => admin_galleries_path},
  {:text => 'Alterando galeria'},
])
%>
<article class="module width_full">
  <header><h3>Alterando galeria</h3></header>
  <%= render 'form' %>
</article>

<article class="module width_full">
  <header>
    <h3 class="tabs_involved">Imagens da galeria</h3>
    <ul class="tabs">
      <li class="active"><a href="#tab1">Imagens</a></li>
      <li><a href="#tab2">Comentários</a></li>
    </ul>
  </header>
  
  <div class="tab_container">
    <div id="tab1" class="tab_content">
      <%= render 'form_gallery_images' %>
    </div>
    <div id="tab2" class="tab_content">
      <%= render 'form_gallery_image_comments' %>
    </div>
  </div>
</article>

app/views/admin/galleries/index.html.erb
<%
title 'Galerias'
breadcrumbs([
  {:text => 'Galerias'}
])
%>

<article class="module width_full">
  <header>
    <h3>Lista de Galerias </h3>
    
  </header>
  <%=button_new('Criar galeria',new_admin_gallery_path)%>
  

  <table class="tablesorter" cellspacing="0"> 
    <thead> 
      <tr> 
        <!-- <th class="header"></th>  -->
        <th width="250" class="header">Título</th> 
        <th class="header">Categoria</th> 
        <th class="header">Local</th> 
        <th class="header">Evento</th> 
        <th class="header">Realizada em</th> 
        <th class="header">Ações</th> 
      </tr> 
    </thead> 
    <tbody> 
      <% @galleries.each do |gallery| %>
      <tr> 
        <!-- <td><input type="checkbox"></td>  -->
        <td><%= gallery.title %></td> 
        <td><%= gallery.gallery_category.name if gallery.gallery_category %></td> 
        <td><%= gallery.place.name if gallery.place %></td> 
        <td><%= gallery.event.title if gallery.event %></td> 
        <td><%= l gallery.realized_at, :format => :short %></td> 
        <td><%= actions_common(gallery)%></td> 
      </tr> 
      <% end %>

    </tbody> 
  </table>
  
  <%=will_paginate @galleries%>
</article>

app/views/admin/galleries/new.html.erb
<%
title 'Galerias - Nova Galeria'
breadcrumbs([
  {:text => 'Galerias', :url => admin_galleries_path},
  {:text => 'Nova galeria'},
])
%>
<article class="module width_full">
  <header><h3>Nova galeria</h3></header>
  <%= render 'form' %>
</article>

app/views/admin/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @admin_gallery.event %>
</p>

<p>
  <b>Place:</b>
  <%= @admin_gallery.place %>
</p>

<p>
  <b>Gallery category:</b>
  <%= @admin_gallery.gallery_category %>
</p>

<p>
  <b>Type gallery:</b>
  <%= @admin_gallery.type_gallery %>
</p>

<p>
  <b>Photographe:</b>
  <%= @admin_gallery.photographe %>
</p>

<p>
  <b>Gallery image:</b>
  <%= @admin_gallery.gallery_image %>
</p>

<p>
  <b>Title:</b>
  <%= @admin_gallery.title %>
</p>

<p>
  <b>Description:</b>
  <%= @admin_gallery.description %>
</p>

<p>
  <b>Realized at:</b>
  <%= @admin_gallery.realized_at %>
</p>


<%= link_to 'Edit', edit_admin_gallery_path(@admin_gallery) %> |
<%= link_to 'Back', admin_galleries_path %>