config/routes.rb
Agitosemana::Application.routes.draw do
  match "garota" => 'garota#index'

  get "busca/resultados"

  get "login/index"
  
  match "principal" => 'home#principal', :as => :principal

  match "albuns-de/:user_id" => 'albuns#index', :as => :albuns
  match "albuns/detalhes/:id" => 'albuns#detalhes', :as => :detalhes_album
  match "albuns/criar" => 'albuns#criar', :as => :criar_album, :via => :post
  match "albuns/:album_id/adicionar-fotos" => 'albuns#adicionar_fotos', :as => :adicionar_fotos
  match "albuns/:album_id/salvar-foto" => 'albuns#salvar_foto', :as => :salvar_foto, :via => :post
  
  match "albuns/:album_id/:id/remover-foto" => 'albuns#remover_foto', :as => :remover_foto
  

  match "albuns/:album_id/ver-foto/:id" => 'albuns_fotos#ver', :as => :album_ver_foto
  match 'albuns/salvar-marcacao' => 'albuns_fotos#salvar_marcacao', :as => :album_salvar_marcacao, :via => :get
  match 'albuns/remover-marcacao' => 'albuns_fotos#remover_marcacao', :as => :album_remover_marcacao, :via => :get
  match 'albuns/fotos/marcacoes' => 'albuns_fotos#marcacoes', :as => :album_marcacoes, :via => :get

  match "entrar" => 'usuarios#index', :as => :entrar
  
  match "registrar" => "usuarios#registrar", :as => :usuarios_registrar

  post "usuarios/entrar"
  
  post "usuarios/criar"
  
  get "usuarios/autocomplete"
  
  match "sair" => "usuarios#sair", :as => :usuarios_sair

  match "chame-agito" => "agito#chame_agito", :as => 'chame_agito'
  match "chame-agito/enviar" => "agito#enviar_chame_agito", :as => 'enviar_chame_agito'
  

  match "fale-conosco" => "agito#fale_conosco", :as => 'fale_conosco'
  match "fale-conosco/enviar" => "agito#enviar_fale_conosco", :as => 'enviar_fale_conosco', :via => :post

  match "15-anos" => "agito#index_15_anos", :as => 'index_15_anos'
  match "15-anos/enviar" => "agito#enviar_15_anos", :as => 'enviar_15_anos'

  match "noticias" => "noticias#index", :as => 'noticias'
  match "noticias/detalhes/:id" => "noticias#detalhes", :as => 'detalhes_noticia'

  match "videos" => "videos#index", :as => 'videos'
  get "videos/detalhes"

  match "agendas" => "agendas#index", :as => 'agendas'
  match "agendas/detalhes/:id" => "agendas#detalhes", :as => 'detalhes_agenda'

  match "galerias" => "galerias#index", :as => :galerias
  match "galerias/detalhes/:id" => 'galerias#detalhes', :as => :detalhes_galeria
  match "galerias/:gallery_id/ver-foto/:id" => 'galerias_fotos#ver', :as => :galeria_ver_foto
  match "galerias/:gallery_id/comentar-foto/:id" => 'galerias_fotos#comentar', :as => :galeria_comentar_foto

  match "colirios" => "colirios#index", :as => :colirios
  match "colirios/detalhes/:id" => 'colirios#detalhes', :as => :detalhes_colirio
  
  
  match "revistas" => "revistas#index", :as => 'revistas'
  match "revistas/detalhes/:id" => "revistas#detalhes", :as => 'detalhes_revista'

  namespace :admin do
    root :to => "events#index"
    
    match 'login/index'               => 'login#index',   :as => :login
    match 'login/logout'              => 'login#logout',  :as => :logout
    match 'login/enter'               => 'login#enter',   :as => :login_enter, :via => :post
    
    
    resources :events
    resources :event_categories
    
    resources :user_albuns
    resources :galleries do
      resources :gallery_images do
        member do
          get :make_special
        end
      end
    end
    resources :gallery_categories
    
    resources :videos
    resources :video_categories
    
    resources :places
    
    resources :polls
    
    resources :news
    resources :news_categories
    resources :column_text_news
    resources :columnists
    
    resources :banners
    resources :magazines
    
    resources :users
    
    
  end
  

  root :to => 'home#index'
end

app/models/event.rb
# -*- encoding : utf-8 -*-
class Event < ActiveRecord::Base
  # default_scope order("realized_at DESC")
  belongs_to :event_category
  belongs_to :place
  has_many :galleries
  attr_accessible :address, :description, :is_special, :latitude, :longitude, :photo, :realized_at, :show_in_front, :title, :event_category_id, :place_id
  validates_presence_of :title, :realized_at, :event_category_id
  has_attached_file :photo, :styles => {:home => '350x390', :medium => "350", :big => "400"}
end

app/controllers/admin/events_controller.rb
# -*- encoding : utf-8 -*-
class Admin::EventsController < Admin::AdminController

  uses_tiny_mce(:options => AppConfig.default_mce_options, :only => [:new, :edit])
  
  # GET /admin/events
  # GET /admin/events.json
  def index
    @events = Event.order("realized_at DESC").paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @events }
    end
  end

  # GET /admin/events/1
  # GET /admin/events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /admin/events/new
  # GET /admin/events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /admin/events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /admin/events
  # POST /admin/events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to [:admin, @event], :notice => 'Evento criado com sucesso.' }
        format.json { render :json => @event, :status => :created, :location => @event }
      else
        flash[:error] = 'Erro ao criar o evento'
        format.html { render :action => "new" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/events/1
  # PUT /admin/events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to [:admin,@event], :notice => 'Evento atualizado com sucesso!' }
        format.json { head :no_content }
      else
        flash[:error] = 'Erro ao atualizar o evento'
        format.html { render :action => "edit" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/events/1
  # DELETE /admin/events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to admin_events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/events_controller.rb
# -*- encoding : utf-8 -*-
class EventsController < ApplicationController

  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, :notice => 'Event was successfully created.' }
        format.json { render :json => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, :notice => 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/events_helper.rb
# -*- encoding : utf-8 -*-
module Admin::EventsHelper
  def events_choices
    Event.all.collect{|t| ["#{t.title} - #{l(t.realized_at,:format => :short)}",t.id]}
  end
end

app/helpers/events_helper.rb
# -*- encoding : utf-8 -*-
module EventsHelper
end

app/views/admin/events/_form.html.erb
<%= simple_form_for([:admin,@event], :html => { :multipart => true }) do |f| %>
<div class="module_content">


  <fieldset>
    <%=f.input :title%>
  </fieldset>
  
  <fieldset>
    <%=f.input :realized_at, :input_html => {:style => 'width:auto;margin:0 2px;'} %>
  </fieldset>
  
  <fieldset>
    <%=f.input :photo%>
  </fieldset>
  
  <% unless @event.photo_file_name.blank? %>
  <fieldset>
    <label>Imagem atual</label>
    <%=link_to @event.photo_file_name, @event.photo.url, :target => "_blank"%>
  </fieldset>
  <% end %>
  
  <fieldset>
    <%=f.association :event_category%>
  </fieldset>
  
  <fieldset>
    <%=f.association :place%>
  </fieldset>
  
  <fieldset>
    <%=f.input :address%>
  </fieldset>
  
  <fieldset>
    <%=f.label :description%>
  </fieldset>
  <%= f.text_area :description, :rows => 15, :cols => 100, :class => 'mceEditor' %>
  <fieldset>
    <%= f.input :show_in_front %>
  </fieldset>
  <fieldset>
    <%= f.input :is_special %>
  </fieldset>
  
  
</div>
<footer>
  <div class="submit_link">
    <%= f.button :submit, :value => 'Salvar', :class => 'alt_btn' %>
  </div>
</footer>
<% end %>
<% content_for :head do %>
<%= javascript_include_tiny_mce_if_used %>
<%= tiny_mce if using_tiny_mce? %>
<% end %>

app/views/admin/events/edit.html.erb
<%
title 'Eventos - Alterando Evento'
breadcrumbs([
  {:text => 'Eventos', :url => admin_events_path},
  {:text => 'Alterando evento'},
])
%>
<article class="module width_full">
  <header><h3>Alterando evento <%=@event.title %></h3></header>
  <%= render 'form' %>
</article>

app/views/admin/events/index.html.erb
<%
title 'Eventos'
breadcrumbs([
  {:text => 'Eventos'}
])
%>

<article class="module width_full">
  <header>
    <h3>Lista de Eventos </h3>
    
  </header>
  <%=button_new('Criar evento',new_admin_event_path)%>
  


  <table class="tablesorter" cellspacing="0"> 
    <thead> 
      <tr> 
        <!-- <th class="header"></th>  -->
        <th class="header">Título</th> 
        <th class="header">Categoria</th> 
        <th class="header">Realizar em</th> 
        <th class="header">Ações</th> 
      </tr> 
    </thead> 
    <tbody> 
      <% @events.each do |event| %>
      <tr> 
        <!-- <td><input type="checkbox"></td>  -->
        <td><%= event.title %></td> 
        <td><%= event.event_category.name %></td> 
        <td><%= l event.realized_at, :format => :short %></td> 
        <td><%= actions_common(event)%></td> 
      </tr> 
      <% end %>

    </tbody> 
  </table>
  
  <%=will_paginate @events%>
</article>

app/views/admin/events/new.html.erb
<%
title 'Eventos - Novo Evento'
breadcrumbs([
  {:text => 'Eventos', :url => admin_events_path},
  {:text => 'Novo evento'},
])
%>
<article class="module width_full">
  <header><h3>Novo evento</h3></header>
  <%= render 'form' %>
</article>

app/views/admin/events/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_event_path(@admin_event) %> |
<%= link_to 'Back', admin_events_path %>