config/routes.rb
Agitosemana::Application.routes.draw do
  match "garota" => 'garota#index'

  get "busca/resultados"

  get "login/index"
  
  match "principal" => 'home#principal', :as => :principal

  match "albuns-de/:user_id" => 'albuns#index', :as => :albuns
  match "albuns/detalhes/:id" => 'albuns#detalhes', :as => :detalhes_album
  match "albuns/criar" => 'albuns#criar', :as => :criar_album, :via => :post
  match "albuns/:album_id/adicionar-fotos" => 'albuns#adicionar_fotos', :as => :adicionar_fotos
  match "albuns/:album_id/salvar-foto" => 'albuns#salvar_foto', :as => :salvar_foto, :via => :post
  
  match "albuns/:album_id/:id/remover-foto" => 'albuns#remover_foto', :as => :remover_foto
  

  match "albuns/:album_id/ver-foto/:id" => 'albuns_fotos#ver', :as => :album_ver_foto
  match 'albuns/salvar-marcacao' => 'albuns_fotos#salvar_marcacao', :as => :album_salvar_marcacao, :via => :get
  match 'albuns/remover-marcacao' => 'albuns_fotos#remover_marcacao', :as => :album_remover_marcacao, :via => :get
  match 'albuns/fotos/marcacoes' => 'albuns_fotos#marcacoes', :as => :album_marcacoes, :via => :get

  match "entrar" => 'usuarios#index', :as => :entrar
  
  match "registrar" => "usuarios#registrar", :as => :usuarios_registrar

  post "usuarios/entrar"
  
  post "usuarios/criar"
  
  get "usuarios/autocomplete"
  
  match "sair" => "usuarios#sair", :as => :usuarios_sair

  match "chame-agito" => "agito#chame_agito", :as => 'chame_agito'
  match "chame-agito/enviar" => "agito#enviar_chame_agito", :as => 'enviar_chame_agito'
  

  match "fale-conosco" => "agito#fale_conosco", :as => 'fale_conosco'
  match "fale-conosco/enviar" => "agito#enviar_fale_conosco", :as => 'enviar_fale_conosco', :via => :post

  match "15-anos" => "agito#index_15_anos", :as => 'index_15_anos'
  match "15-anos/enviar" => "agito#enviar_15_anos", :as => 'enviar_15_anos'

  match "noticias" => "noticias#index", :as => 'noticias'
  match "noticias/detalhes/:id" => "noticias#detalhes", :as => 'detalhes_noticia'

  match "videos" => "videos#index", :as => 'videos'
  get "videos/detalhes"

  match "agendas" => "agendas#index", :as => 'agendas'
  match "agendas/detalhes/:id" => "agendas#detalhes", :as => 'detalhes_agenda'

  match "galerias" => "galerias#index", :as => :galerias
  match "galerias/detalhes/:id" => 'galerias#detalhes', :as => :detalhes_galeria
  match "galerias/:gallery_id/ver-foto/:id" => 'galerias_fotos#ver', :as => :galeria_ver_foto
  match "galerias/:gallery_id/comentar-foto/:id" => 'galerias_fotos#comentar', :as => :galeria_comentar_foto

  match "colirios" => "colirios#index", :as => :colirios
  match "colirios/detalhes/:id" => 'colirios#detalhes', :as => :detalhes_colirio
  
  
  match "revistas" => "revistas#index", :as => 'revistas'
  match "revistas/detalhes/:id" => "revistas#detalhes", :as => 'detalhes_revista'

  namespace :admin do
    root :to => "events#index"
    
    match 'login/index'               => 'login#index',   :as => :login
    match 'login/logout'              => 'login#logout',  :as => :logout
    match 'login/enter'               => 'login#enter',   :as => :login_enter, :via => :post
    
    
    resources :events
    resources :event_categories
    
    resources :user_albuns
    resources :galleries do
      resources :gallery_images do
        member do
          get :make_special
        end
      end
    end
    resources :gallery_categories
    
    resources :videos
    resources :video_categories
    
    resources :places
    
    resources :polls
    
    resources :news
    resources :news_categories
    resources :column_text_news
    resources :columnists
    
    resources :banners
    resources :magazines
    
    resources :users
    
    
  end
  

  root :to => 'home#index'
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index
  end
  
  def principal
    render :action => :index
  end
end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/views/home/index.html.erb
<div id="middle-full-banner">
  <div class="wrap">
  <div id="slide-holder">
    <div id="slide-runner">
      <% middle_big_banners.each_with_index do |banner,i| %>
      <%=print_banner(banner, :middle_big, {:id => "slide-img-#{i}", :class => 'slide'})%>
      <% end %>
      <div id="slide-controls">
        <p id="slide-client" class="text"><strong></strong><span></span></p>
        <p id="slide-nav"></p>
      </div>
    </div>

    <!--content featured gallery here -->
  </div>
  </div>
</div>
<div class="clear"></div>
<div id="list-news">
  <h1 class="green">notícias</h1>
  <% last_2_news.each do |news| %>
  <%= link_to image_tag(news.photo.url(:home), :size => '370x152', :class => 'to-fade'), detalhes_noticia_path(news)%>
  <h3><%=link_to truncate(news.title, :length => 46), detalhes_noticia_path(news)%></h3>
  <% end %>
</div>
<div id="next-events">
  <h1 class="clean-blue">agenda</h1>
  <%=link_to(image_tag('agenda.jpg', :class => 'to-fade'), 'https://www.facebook.com/agitooficial?fref=ts', target: '_blank')%>
</div>
<div class="clear"></div>

<div id="last-video">
  <h1 class="green">vídeo em destaque</h1>
  <%=raw yt_client.video_by(Video.first.url).embed_html_with_width(368)   %>
</div>
<div id="last-twitter-messages">
  <h1 class="clean-blue">divulgue aqui</h1>
  <%= home_middle_banner %>
</div>
<div class="clear"></div>




<div class="clear"></div>
<div id="list-galleries">
  <h1 class="red">últimos agitos</h1>
  <% last_6_galleries.in_groups_of(3,false).each do |galleries_group| %>
  <% galleries_group.each_with_index do |gallery,i| %>
  <div class="gallery-box <%='first' if i == 0%>">
    <%= link_to image_tag(gallery.image_front.url(:home), :size => '238x92', :class => 'to-fade'), detalhes_galeria_path(gallery) -%>
    <h3><%=link_to truncate(gallery.title, :length => 38), detalhes_galeria_path(gallery)%></h3>
  </div>
  <% end %>
  <% end %>
</div>
<div class="clear"></div>
<% if last_collyrium %>
<div id="last-collyrium">
  <h1 class="purpple">garota da semana</h1>
  <%=link_to(image_tag(last_collyrium.image_front.url(:home_big), :size => '750x300', :class => 'to-fade'),detalhes_colirio_path(last_collyrium))%>
</div>
<div class="clear"></div>
<% end %>

<div id="footer-full-banner">
  <%=footer_full_banner%>
</div>

<% if controller.action_name == 'index' && !front_banner.nil? %>
<div id="front-banner" style="display:none">
  <h2 class="green" onclick="window.location.href='<%=principal_path%>'" style="cursor:pointer">Ir para o Agito</h2>
  <%=front_banner%>
</div>
<% end %>





<% content_for :head do %>
<%= stylesheet_link_tag 'frontend/home', 'frontend/slider' %>


<script type="text/javascript" charset="utf-8">
  var _siteRoot='/',_root='/';
</script>

<% if controller.action_name == 'index' && !front_banner.nil? %>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function(){
    // $('#front-banner').show();
    
    $('#front-banner').dialog({
      width: 924,
      modal: true,
      position: ['center','top'],
      show: { effect: 'drop', direction: "up" },
      resizable: false,
      draggable: false,
      title: 'Anúncio',
      close: function(event, ui) {
        window.location.href='<%=principal_path%>'
      }
    });
    // $(document.body).qtip(
    //      {
    //        id: 'modal', // Since we're only creating one modal, give it an ID so we can style it
    //        content: {
    //          text: $('#front-banner'),
    //          title: {
    //            text: 'Agito da Semana',
    //            button: false
    //          }
    //        },
    //        position: {
    //           my: 'top center', // ...at the center of the viewport
    //          at: 'top center',
    //          target: $(window),
    //          viewport: $(window)
    //        },
    //        show: {
    //           // event: 'click', // Show it on click...
    //          solo: true, // ...and hide all other tooltips...
    //          modal: true,
    //          ready: true
    //        },
    //        hide: false,
    //        style: 'ui-tooltip-light ui-tooltip-rounded'
    //      });
  })
</script>
<% end %>


<%= javascript_include_tag 'frontend/slider' %>

<script type="text/javascript" charset="utf-8">
if(!window.slider) var slider={};slider.data=<%=raw middle_big_banners.collect{|banner| {:id => "slide-img-#{middle_big_banners.index(banner)}", :client => banner.title, :desc => ''}}.to_json%>

$(document).ready(function(){
  
  $('.to-fade').each(function() {
    $(this).hover(
      function() {
        $(this).stop().animate({ opacity: 1.0 });
      },
      function() {
        $(this).stop().animate({ opacity: 0.85 });
      })
    });
})
</script>
<% end %>