config/routes.rb
Agitosemana::Application.routes.draw do
  match "garota" => 'garota#index'

  get "busca/resultados"

  get "login/index"
  
  match "principal" => 'home#principal', :as => :principal

  match "albuns-de/:user_id" => 'albuns#index', :as => :albuns
  match "albuns/detalhes/:id" => 'albuns#detalhes', :as => :detalhes_album
  match "albuns/criar" => 'albuns#criar', :as => :criar_album, :via => :post
  match "albuns/:album_id/adicionar-fotos" => 'albuns#adicionar_fotos', :as => :adicionar_fotos
  match "albuns/:album_id/salvar-foto" => 'albuns#salvar_foto', :as => :salvar_foto, :via => :post
  
  match "albuns/:album_id/:id/remover-foto" => 'albuns#remover_foto', :as => :remover_foto
  

  match "albuns/:album_id/ver-foto/:id" => 'albuns_fotos#ver', :as => :album_ver_foto
  match 'albuns/salvar-marcacao' => 'albuns_fotos#salvar_marcacao', :as => :album_salvar_marcacao, :via => :get
  match 'albuns/remover-marcacao' => 'albuns_fotos#remover_marcacao', :as => :album_remover_marcacao, :via => :get
  match 'albuns/fotos/marcacoes' => 'albuns_fotos#marcacoes', :as => :album_marcacoes, :via => :get

  match "entrar" => 'usuarios#index', :as => :entrar
  
  match "registrar" => "usuarios#registrar", :as => :usuarios_registrar

  post "usuarios/entrar"
  
  post "usuarios/criar"
  
  get "usuarios/autocomplete"
  
  match "sair" => "usuarios#sair", :as => :usuarios_sair

  match "chame-agito" => "agito#chame_agito", :as => 'chame_agito'
  match "chame-agito/enviar" => "agito#enviar_chame_agito", :as => 'enviar_chame_agito'
  

  match "fale-conosco" => "agito#fale_conosco", :as => 'fale_conosco'
  match "fale-conosco/enviar" => "agito#enviar_fale_conosco", :as => 'enviar_fale_conosco', :via => :post

  match "15-anos" => "agito#index_15_anos", :as => 'index_15_anos'
  match "15-anos/enviar" => "agito#enviar_15_anos", :as => 'enviar_15_anos'

  match "noticias" => "noticias#index", :as => 'noticias'
  match "noticias/detalhes/:id" => "noticias#detalhes", :as => 'detalhes_noticia'

  match "videos" => "videos#index", :as => 'videos'
  get "videos/detalhes"

  match "agendas" => "agendas#index", :as => 'agendas'
  match "agendas/detalhes/:id" => "agendas#detalhes", :as => 'detalhes_agenda'

  match "galerias" => "galerias#index", :as => :galerias
  match "galerias/detalhes/:id" => 'galerias#detalhes', :as => :detalhes_galeria
  match "galerias/:gallery_id/ver-foto/:id" => 'galerias_fotos#ver', :as => :galeria_ver_foto
  match "galerias/:gallery_id/comentar-foto/:id" => 'galerias_fotos#comentar', :as => :galeria_comentar_foto

  match "colirios" => "colirios#index", :as => :colirios
  match "colirios/detalhes/:id" => 'colirios#detalhes', :as => :detalhes_colirio
  
  
  match "revistas" => "revistas#index", :as => 'revistas'
  match "revistas/detalhes/:id" => "revistas#detalhes", :as => 'detalhes_revista'

  namespace :admin do
    root :to => "events#index"
    
    match 'login/index'               => 'login#index',   :as => :login
    match 'login/logout'              => 'login#logout',  :as => :logout
    match 'login/enter'               => 'login#enter',   :as => :login_enter, :via => :post
    
    
    resources :events
    resources :event_categories
    
    resources :user_albuns
    resources :galleries do
      resources :gallery_images do
        member do
          get :make_special
        end
      end
    end
    resources :gallery_categories
    
    resources :videos
    resources :video_categories
    
    resources :places
    
    resources :polls
    
    resources :news
    resources :news_categories
    resources :column_text_news
    resources :columnists
    
    resources :banners
    resources :magazines
    
    resources :users
    
    
  end
  

  root :to => 'home#index'
end

app/controllers/galerias_controller.rb
# -*- encoding : utf-8 -*-
class GaleriasController < ApplicationController
  def index
    @galleries = Gallery.common.paginate(:page => params[:page], :per_page => 18)
  end
  
  def detalhes
    @gallery = Gallery.find(params[:id])
  end

  
end

app/helpers/galerias_helper.rb
# -*- encoding : utf-8 -*-
module GaleriasHelper
  def last_6_galleries
    Gallery.common.limit(6)
  end
end

app/views/galerias/_show.html.erb
<div id="top-image">
  <%=image_tag gallery.image_front.url(:big)%><br />
  <iframe src="//www.facebook.com/plugins/like.php?href=<%=request.url%>&amp;send=false&amp;layout=button_count&amp;width=400&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=tahoma&amp;height=21" scrolling="no" frameborder="0" style="margin-top:10px;border:none; overflow:hidden; width:400px; height:21px;" allowTransparency="true"></iframe>
</div>
<div id="details">
<ul class="disc">
  <li>Realizar em: <strong><%=l gallery.realized_at %></strong></li>
  <% if gallery.place %>
  <li>Local: <strong><%= gallery.place.name%></strong></li>
  <li><%= gallery.place.address %></li>
  <% end %>
  <% if gallery.event %>
  <li>Evento associado: <strong><%= link_to gallery.event.title, detalhes_agenda_path(gallery.event)%></strong></li>
  <% end %>
  <% unless gallery.photographers.blank? %>
  <li>Fotógrafo(s): <strong><%= gallery.photographers%></strong></li>
  <% end %>
  <li>Categoria: <strong><%=gallery.gallery_category.name%></strong></li>
</ul>
<%=simple_format gallery.description%>
</div>
<div class="clear"></div>
<h2><%=gallery.gallery_images.count%> fotos</h2>
<ul id="images-carousel" class="jcarousel-skin-tango">
  <% gallery.gallery_images.each do |gallery_image|%>
  <li>
  <%=link_to(image_tag(gallery_image.image.url(:thumb)),galeria_ver_foto_path(gallery_image.gallery,gallery_image), :class => 'gallery_image_modal', :rel => 'gallery_images')%>
  <br />
  <%=link_to('baixar',gallery_image.image.url(:detail), :target => '_blank')%>
  </li>
  <% end %>
</ul>

<% content_for :head do %>
<%=stylesheet_link_tag 'frontend/galerias','colorbox'%>
<%=javascript_include_tag 'frontend/jquery.colorbox'%>

<%=javascript_tag do%>


$(document).ready(function() {
  $('#images-carousel').jcarousel({visible: 7});
  $('.gallery_image_modal').colorbox({ width: '850px', height: '100%', rel:'gallery_images'});
});
<% end %>
<% end %>

app/views/galerias/colirio.html.erb
<h1>Galerias#colirio</h1>
<p>Find me in app/views/galerias/colirio.html.erb</p>

app/views/galerias/detalhes.html.erb
<h1 class="red">agito</h1>
<h2 class="red">:) <%=@gallery.title%></h2>
<% content_for :title do %>
<%=@gallery.title%>
<% end %>

<%=render :partial => 'galerias/show', :locals => {:gallery => @gallery}%>

app/views/galerias/fotos.html.erb
<h1>Galerias#fotos</h1>
<p>Find me in app/views/galerias/fotos.html.erb</p>

app/views/galerias/index.html.erb
<div id="list-galleries">
  <h1 class="red">últimos agitos</h1>
  <% @galleries.in_groups_of(3,false).each do |galleries_group| %>
  <% galleries_group.each_with_index do |gallery,i| %>
  <div class="gallery-box box-list <%='first' if i == 0%>">
    <%= link_to image_tag(gallery.image_front.url(:home), :size => '238x92', :alt => gallery.title), detalhes_galeria_path(gallery), :title => gallery.title -%>
    <h3><%=link_to truncate(gallery.title, :length => 25), detalhes_galeria_path(gallery), :title => gallery.title%> - <%=l gallery.realized_at.to_date, :format => :default%></h3>
  </div>
  <% end %>
  <% end %>
  <div class="clear"></div>
  <%=will_paginate @galleries%>
</div>
<div class="clear"></div>


<% content_for :head do %>
<%=stylesheet_link_tag 'frontend/home'%>
<% end %>